/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.voting.Admin;

import e.voting.Login;
import e.voting.Voter.AddVoter;
import e.voting.Voter.VoterInformation;
import e.voting.candidiate.AddCandidiate;
import e.voting.candidiate.CandidiateInfo;
import e.voting.resultshow.ResultShow;
import e.voting.timeset.SetTime;
import java.awt.Color;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

import party.AddParty;
import party.ManageParty;
import post.AddPost;
import post.ManagePost;

/**
 *
 * @author DELL
 */
public class AdminDashboard extends javax.swing.JFrame {

    int id;
    public AdminDashboard(int id) {
        init();
        this.id=id;
    }
    public AdminDashboard(){
        init();
        
    }
    private void init(){
        initComponents();
        setTitle("E-Voting System");
        ImageIcon icon=new ImageIcon("image/12.jpg");        
        setIconImage(icon.getImage());
        Clock();
        
        setLocationRelativeTo(null);
    }
    private void Clock(){
        Thread clock=new Thread(){
          public void run(){
            try {
                for(;;){
                Calendar cal = new GregorianCalendar();
        
                int day = cal.get(Calendar.DAY_OF_MONTH);
                int month = cal.get(Calendar.MONTH);
                int year = cal.get(Calendar.YEAR);
                //date.setText("Current Date:" + day + "/" + (month + 1) + "/" + year);
                //time.setForeground(Color.White);

                int second = cal.get(Calendar.SECOND);
                int minute = cal.get(Calendar.MINUTE);
                int hour = cal.get(Calendar.HOUR);
                //time.setText("Current Time:" + hour + ":" + minute + ":" + second);
              sleep(1000);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
          }
        };
        clock.start();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton7 = new javax.swing.JButton();
        btnCreateAdmin = new javax.swing.JButton();
        toolVoter = new javax.swing.JButton();
        toolCandidiae = new javax.swing.JButton();
        manageAdmin = new javax.swing.JButton();
        manageVoter = new javax.swing.JButton();
        manageCandi = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        barResult = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        toolShowProfile = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        exitmenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuCreateAdmin = new javax.swing.JMenuItem();
        manageToolAdmin = new javax.swing.JMenuItem();
        toolProfile = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        createVoterMenu = new javax.swing.JMenuItem();
        manageVoterMenu = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        createCanMenu = new javax.swing.JMenuItem();
        manageCanMenu = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        toolAddparty = new javax.swing.JMenuItem();
        toolmanagePart = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        toolAddPost = new javax.swing.JMenuItem();
        toolManagePost = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        viewResultMenu = new javax.swing.JMenuItem();
        manageResultMenu = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        startTimeMenu = new javax.swing.JMenuItem();
        endTimeMenu = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        onlinehelp = new javax.swing.JMenuItem();
        offlinehelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(255, 204, 255));
        jToolBar1.setRollover(true);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/001_home-32.png"))); // NOI18N
        jButton7.setText("Home");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton7);

        btnCreateAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UI_Blue_2_of_3_1-32.png"))); // NOI18N
        btnCreateAdmin.setText("Create Admin");
        btnCreateAdmin.setFocusable(false);
        btnCreateAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreateAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCreateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAdminActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCreateAdmin);

        toolVoter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/057_user_security-32.png"))); // NOI18N
        toolVoter.setText("Create Voter");
        toolVoter.setFocusable(false);
        toolVoter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolVoter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolVoterActionPerformed(evt);
            }
        });
        jToolBar1.add(toolVoter);

        toolCandidiae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UI_Blue_2_of_3_1-32.png"))); // NOI18N
        toolCandidiae.setText("Create Candidiate");
        toolCandidiae.setFocusable(false);
        toolCandidiae.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolCandidiae.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolCandidiae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolCandidiaeActionPerformed(evt);
            }
        });
        jToolBar1.add(toolCandidiae);

        manageAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/server-32.png"))); // NOI18N
        manageAdmin.setText("Manage Admin");
        manageAdmin.setFocusable(false);
        manageAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        manageAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        manageAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdminActionPerformed(evt);
            }
        });
        jToolBar1.add(manageAdmin);

        manageVoter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/server-32.png"))); // NOI18N
        manageVoter.setText("Manage Voter");
        manageVoter.setFocusable(false);
        manageVoter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        manageVoter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        manageVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVoterActionPerformed(evt);
            }
        });
        jToolBar1.add(manageVoter);

        manageCandi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/server-32.png"))); // NOI18N
        manageCandi.setText("Manage Candidiate");
        manageCandi.setFocusable(false);
        manageCandi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        manageCandi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        manageCandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCandiActionPerformed(evt);
            }
        });
        jToolBar1.add(manageCandi);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/13-32.png"))); // NOI18N
        jButton4.setText("Time Set");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        barResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/073_view_show-32.png"))); // NOI18N
        barResult.setText("Result");
        barResult.setFocusable(false);
        barResult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barResult.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barResultActionPerformed(evt);
            }
        });
        jToolBar1.add(barResult);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/49-32.png"))); // NOI18N
        logout.setText("Logout");
        logout.setFocusable(false);
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jToolBar1.add(logout);

        toolShowProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/025 (1).png"))); // NOI18N
        toolShowProfile.setText("Profiles");
        toolShowProfile.setFocusable(false);
        toolShowProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolShowProfile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolShowProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolShowProfileActionPerformed(evt);
            }
        });
        jToolBar1.add(toolShowProfile);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 130, 265, 36));

        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 60, 242, 38));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Electronic Voting");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 278, 349, 59));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/people-give-vote-raise-his-hand-blue-background-illustration-67261399.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1300, 500));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/people-give-vote-raise-his-hand-blue-background-illustration-67261399.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 500));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/people-give-vote-raise-his-hand-blue-background-illustration-67261399.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 1300, 500));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/people-give-vote-raise-his-hand-blue-background-illustration-67261399.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 1300, 480));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/163_plus_add_new-20.png"))); // NOI18N
        jMenuItem1.setText("open");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Save");
        jMenu1.add(jMenuItem2);

        exitmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        exitmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/010_x-3-20.png"))); // NOI18N
        exitmenu.setText("Exit");
        exitmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitmenuActionPerformed(evt);
            }
        });
        jMenu1.add(exitmenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Admin");

        menuCreateAdmin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuCreateAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UI_Blue_2_of_3_1-20.png"))); // NOI18N
        menuCreateAdmin.setText("Create");
        menuCreateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreateAdminActionPerformed(evt);
            }
        });
        jMenu3.add(menuCreateAdmin);

        manageToolAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/server-20.png"))); // NOI18N
        manageToolAdmin.setText("Manage");
        manageToolAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageToolAdminActionPerformed(evt);
            }
        });
        jMenu3.add(manageToolAdmin);

        toolProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/025 (3).png"))); // NOI18N
        toolProfile.setText("Profile");
        toolProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolProfileActionPerformed(evt);
            }
        });
        jMenu3.add(toolProfile);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Voter");

        createVoterMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        createVoterMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/057_user_security-16.png"))); // NOI18N
        createVoterMenu.setText("Create");
        createVoterMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVoterMenuActionPerformed(evt);
            }
        });
        jMenu4.add(createVoterMenu);

        manageVoterMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/server-20.png"))); // NOI18N
        manageVoterMenu.setText("Manage");
        manageVoterMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVoterMenuActionPerformed(evt);
            }
        });
        jMenu4.add(manageVoterMenu);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Candidiate");

        createCanMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        createCanMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UI_Blue_2_of_3_1-20.png"))); // NOI18N
        createCanMenu.setText("Create");
        createCanMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCanMenuActionPerformed(evt);
            }
        });
        jMenu5.add(createCanMenu);

        manageCanMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/server-20.png"))); // NOI18N
        manageCanMenu.setText("Manage");
        manageCanMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCanMenuActionPerformed(evt);
            }
        });
        jMenu5.add(manageCanMenu);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Party");

        toolAddparty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/163_plus_add_new-20.png"))); // NOI18N
        toolAddparty.setText("Add");
        toolAddparty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolAddpartyActionPerformed(evt);
            }
        });
        jMenu6.add(toolAddparty);

        toolmanagePart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/business_corporate_group_office-36-24.png"))); // NOI18N
        toolmanagePart.setText("Manage");
        toolmanagePart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolmanagePartActionPerformed(evt);
            }
        });
        jMenu6.add(toolmanagePart);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Post");

        toolAddPost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/163_plus_add_new-20.png"))); // NOI18N
        toolAddPost.setText("Create");
        toolAddPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolAddPostActionPerformed(evt);
            }
        });
        jMenu7.add(toolAddPost);

        toolManagePost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/business_corporate_group_office-36-24.png"))); // NOI18N
        toolManagePost.setText("Information");
        toolManagePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolManagePostActionPerformed(evt);
            }
        });
        jMenu7.add(toolManagePost);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("View");

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/025 (3).png"))); // NOI18N
        jMenu11.setText("View Old Record");
        jMenu8.add(jMenu11);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Result");

        viewResultMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        viewResultMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/073_view_show-20.png"))); // NOI18N
        viewResultMenu.setText("View");
        viewResultMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewResultMenuActionPerformed(evt);
            }
        });
        jMenu9.add(viewResultMenu);

        manageResultMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        manageResultMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/server-20.png"))); // NOI18N
        manageResultMenu.setText("Manage");
        jMenu9.add(manageResultMenu);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("Time Set");

        startTimeMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        startTimeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/time_sheduled-20.png"))); // NOI18N
        startTimeMenu.setText("Time Start");
        startTimeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTimeMenuActionPerformed(evt);
            }
        });
        jMenu10.add(startTimeMenu);

        endTimeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/010_x-3-20.png"))); // NOI18N
        endTimeMenu.setText("End Time");
        endTimeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTimeMenuActionPerformed(evt);
            }
        });
        jMenu10.add(endTimeMenu);

        jMenuBar1.add(jMenu10);

        jMenu12.setText("Help");

        onlinehelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/011 (3).png"))); // NOI18N
        onlinehelp.setText("Online");
        onlinehelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlinehelpActionPerformed(evt);
            }
        });
        jMenu12.add(onlinehelp);

        offlinehelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/025 (3).png"))); // NOI18N
        offlinehelp.setText("Offline");
        offlinehelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offlinehelpActionPerformed(evt);
            }
        });
        jMenu12.add(offlinehelp);

        jMenuBar1.add(jMenu12);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCreateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreateAdminActionPerformed
        AddAdmin.getObj().setVisible(true);
    }//GEN-LAST:event_menuCreateAdminActionPerformed

    private void createCanMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCanMenuActionPerformed
       AddCandidiate.getObj().setVisible(true);
    }//GEN-LAST:event_createCanMenuActionPerformed

    private void exitmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitmenuActionPerformed
      int c=JOptionPane.showConfirmDialog(this, "Do you really want to close ?","Message",JOptionPane.YES_NO_OPTION);
      if(c==0){
          setVisible(false);          
      }
    }//GEN-LAST:event_exitmenuActionPerformed

    private void createVoterMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVoterMenuActionPerformed
        AddVoter obj=new AddVoter();
        obj.setVisible(true);
    }//GEN-LAST:event_createVoterMenuActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int c=JOptionPane.showConfirmDialog(this, "Do you really want to Log Out ?","Message",JOptionPane.YES_NO_OPTION);
        if(c==0){
            setVisible(false);
            Login obj=new Login();
            obj.setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void toolVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolVoterActionPerformed
        AddVoter.getObj().setVisible(true);
        
    }//GEN-LAST:event_toolVoterActionPerformed

    private void toolCandidiaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolCandidiaeActionPerformed
       AddCandidiate.getObj().setVisible(true);
    }//GEN-LAST:event_toolCandidiaeActionPerformed

    private void manageAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdminActionPerformed
        ManageAdmin.getObj().setVisible(true);
    }//GEN-LAST:event_manageAdminActionPerformed

    private void manageCandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCandiActionPerformed
        CandidiateInfo.getObj().setVisible(true);
    }//GEN-LAST:event_manageCandiActionPerformed

    private void manageVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVoterActionPerformed
         VoterInformation.getObj().setVisible(true);
    }//GEN-LAST:event_manageVoterActionPerformed

    private void manageVoterMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVoterMenuActionPerformed
        VoterInformation.getObj().setVisible(true);
    }//GEN-LAST:event_manageVoterMenuActionPerformed

    private void manageCanMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCanMenuActionPerformed
        CandidiateInfo.getObj().setVisible(true);
    }//GEN-LAST:event_manageCanMenuActionPerformed

    private void toolProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolProfileActionPerformed
       Profile obj=new Profile(id);
       obj.setVisible(true);
    }//GEN-LAST:event_toolProfileActionPerformed

    private void manageToolAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageToolAdminActionPerformed
         ManageAdmin.getObj().setVisible(true);
    }//GEN-LAST:event_manageToolAdminActionPerformed

    private void btnCreateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAdminActionPerformed
         AddAdmin.getObj().setVisible(true);
    }//GEN-LAST:event_btnCreateAdminActionPerformed

    private void toolShowProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolShowProfileActionPerformed
        Profile obj=new Profile(id);
       obj.setVisible(true);
    }//GEN-LAST:event_toolShowProfileActionPerformed

    private void toolAddpartyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolAddpartyActionPerformed
        AddParty.getObj().setVisible(true);
    }//GEN-LAST:event_toolAddpartyActionPerformed

    private void toolmanagePartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolmanagePartActionPerformed
       ManageParty.getObj().setVisible(true);
    }//GEN-LAST:event_toolmanagePartActionPerformed

    private void toolAddPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolAddPostActionPerformed
        AddPost.getObj().setVisible(true);
    }//GEN-LAST:event_toolAddPostActionPerformed

    private void toolManagePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolManagePostActionPerformed
        ManagePost.getObj().setVisible(true);
    }//GEN-LAST:event_toolManagePostActionPerformed

    private void viewResultMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewResultMenuActionPerformed
        ResultShow.getObj().setVisible(true);
    }//GEN-LAST:event_viewResultMenuActionPerformed

    private void barResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barResultActionPerformed
        ResultShow.getObj().setVisible(true);
    }//GEN-LAST:event_barResultActionPerformed

    private void offlinehelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offlinehelpActionPerformed
        try {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + "File\\About.pdf");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error Opening File!!");
        }
    }//GEN-LAST:event_offlinehelpActionPerformed

    private void onlinehelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlinehelpActionPerformed
       try {
            // TODO add your handling code here:
            String url = "https://www.youtube.com/channel/UCdPK2jZJA2pR_6tl9m-kKCw?sub_confirmation=1";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_onlinehelpActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       SetTime obj=new SetTime();
       obj.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void startTimeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTimeMenuActionPerformed
       SetTime obj=new SetTime();
       obj.setVisible(true);
    }//GEN-LAST:event_startTimeMenuActionPerformed

    private void endTimeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTimeMenuActionPerformed
        int c=JOptionPane.showConfirmDialog(this, "Do you want End voting Time","Delete",JOptionPane.YES_NO_OPTION);
            if(c==0){   
                JOptionPane.showMessageDialog(rootPane, "Time Ended for voting Thank you ");
            }
    }//GEN-LAST:event_endTimeMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic ".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barResult;
    private javax.swing.JButton btnCreateAdmin;
    private javax.swing.JMenuItem createCanMenu;
    private javax.swing.JMenuItem createVoterMenu;
    private javax.swing.JLabel date;
    private javax.swing.JMenuItem endTimeMenu;
    private javax.swing.JMenuItem exitmenu;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton logout;
    private javax.swing.JButton manageAdmin;
    private javax.swing.JMenuItem manageCanMenu;
    private javax.swing.JButton manageCandi;
    private javax.swing.JMenuItem manageResultMenu;
    private javax.swing.JMenuItem manageToolAdmin;
    private javax.swing.JButton manageVoter;
    private javax.swing.JMenuItem manageVoterMenu;
    private javax.swing.JMenuItem menuCreateAdmin;
    private javax.swing.JMenuItem offlinehelp;
    private javax.swing.JMenuItem onlinehelp;
    private javax.swing.JMenuItem startTimeMenu;
    private javax.swing.JLabel time;
    private javax.swing.JMenuItem toolAddPost;
    private javax.swing.JMenuItem toolAddparty;
    private javax.swing.JButton toolCandidiae;
    private javax.swing.JMenuItem toolManagePost;
    private javax.swing.JMenuItem toolProfile;
    private javax.swing.JButton toolShowProfile;
    private javax.swing.JButton toolVoter;
    private javax.swing.JMenuItem toolmanagePart;
    private javax.swing.JMenuItem viewResultMenu;
    // End of variables declaration//GEN-END:variables
}
