/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.voting.Voter;

import e.voting.DbConnect;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author DELL
 */
public class AddVoter extends javax.swing.JFrame {

    private static AddVoter obj=null;
    private Connection connection = null;
    private PreparedStatement pst = null;
    private ResultSet resultSet = null; 
    private String filePath = null;
    private String fileName=null;
    private byte[] personImg = null;
    //private String voter_id=null;
    private String mysql=null;
    private String char_list = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXZ1234567890";
    public AddVoter() {
        init();
        
    }
    public AddVoter(String id){
        init();
        
        save.setEnabled(false);  
        update.setEnabled(true);
        FillTheAllField(id);
    }
    private void init(){
        initComponents();
         connection = DbConnect.DbConnect();
         setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setResizable(false);
        setTitle("Add Voter");
        fillAddressDefault();
        update.setEnabled(false);
        display_id.setEditable(false);
    }
    public static AddVoter getObj(){
        if(obj==null){
            obj=new AddVoter();
        }return obj;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_mname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_fathername = new javax.swing.JTextField();
        txt_mothername = new javax.swing.JTextField();
        txt_grandfname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_woda = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        uploadimg = new javax.swing.JButton();
        imgPath = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        display_id = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        addnew = new javax.swing.JButton();
        view = new javax.swing.JButton();
        update = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        dob = new com.toedter.calendar.JDateChooser();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        country = new javax.swing.JComboBox<>();
        pardesh = new javax.swing.JComboBox<>();
        district = new javax.swing.JComboBox<>();
        muncipality = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 90, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Middle Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 80, 31));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date Of Birth:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 120, 32));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mother Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 110, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Father Name:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 120, 31));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Grand Father Name:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 29));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gender:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 60, 31));
        jPanel1.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 85, 180, 31));
        jPanel1.add(txt_mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 180, 31));
        jPanel1.add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 180, 31));
        jPanel1.add(txt_fathername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 180, 31));
        jPanel1.add(txt_mothername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 180, 31));
        jPanel1.add(txt_grandfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 180, 31));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pardesh:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 70, 29));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("District:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 60, 29));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Votting ID:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 80, 29));
        jPanel1.add(txt_woda, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 87, 29));

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ADD VOTER ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 77, 190, 160));

        uploadimg.setText("Upload");
        uploadimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadimgActionPerformed(evt);
            }
        });
        jPanel1.add(uploadimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 243, 73, -1));
        jPanel1.add(imgPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 244, 103, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Here is show Voter Id If click the save button");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, -1, 31));

        display_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_idActionPerformed(evt);
            }
        });
        jPanel1.add(display_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 350, 80, 31));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        addnew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/163_plus_add_new-20.png"))); // NOI18N
        addnew.setText("ADD");
        addnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewActionPerformed(evt);
            }
        });

        view.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/073_view_show-20.png"))); // NOI18N
        view.setText("VIEW");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ID_Card-01-20.png"))); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/831-20.png"))); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save_Icon-24.png"))); // NOI18N
        save.setText("SAVED");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(addnew, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addnew, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 640, -1));
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 180, 30));

        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 60, -1));

        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 70, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Municipality/VDC:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 130, 29));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Country:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 70, 29));

        country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Country", "Nepal", "India", "US", "Germany", "China", "Hongkong", "Bhutan", "Pakistan", "Afaganistan", " " }));
        jPanel1.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 140, 30));

        pardesh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Pardesh", "Koshi Pradesh", "Madhesh Pradesh", "Bagmati Pradesh", "Gandaki Pradesh", "Lumbini Pradesh", "Karnali Pradesh" }));
        pardesh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pardeshItemStateChanged(evt);
            }
        });
        jPanel1.add(pardesh, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 140, 30));

        district.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(district, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 140, 30));

        muncipality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(muncipality, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 140, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Search ID:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 80, 29));

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 150, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Woda No:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 80, 29));

        jPanel5.setBackground(new java.awt.Color(204, 0, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 950, 10));

        jPanel6.setBackground(new java.awt.Color(255, 0, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 10, 380));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        update.setEnabled(true);
        save.setEnabled(false);
        mysql="select * from voter where voter_id like'"+search.getText()+"%'";

        try {
            pst = connection.prepareStatement(mysql);
            resultSet=pst.executeQuery();
            if(resultSet.next()){
                display_id.setText(resultSet.getString("voter_id"));
                txt_fname.setText(resultSet.getString("fname"));
                txt_mname.setText(resultSet.getString("mname"));
                txt_lname.setText(resultSet.getString("lname"));
                txt_fathername.setText(resultSet.getString("father_name"));
                txt_mothername.setText(resultSet.getString("mother_name"));
                txt_grandfname.setText(resultSet.getString("grand_father_name"));
                String dateValue = resultSet.getString("date_of_birth");
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);

                dob.setDate(date);
                if(resultSet.getString("gender").equals("Male")){
                    male.setSelected(true);
                    female.setSelected(false);
                }else{
                    female.setSelected(true);
                    male.setSelected(false);
                }
                byte[] imageData = resultSet.getBytes("image");
                ImageIcon format = new ImageIcon(scaledImage(imageData, img.getWidth(), img.getHeight()));
                img.setIcon(format);
                String c=resultSet.getString("country");
                String p=resultSet.getString("pardesh");
                String d=resultSet.getString("district");
                String m=resultSet.getString("Nagarpalika");
                txt_woda.setText(resultSet.getString("oda_no"));
                country.setSelectedIndex(1);
                pardesh.setSelectedIndex(1);

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_searchKeyReleased

    private void pardeshItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pardeshItemStateChanged
        String key=(String) pardesh.getSelectedItem();

        if(pardesh.getSelectedItem().equals("Koshi Pradesh")){
            fillAddress(key);
        }else if(pardesh.getSelectedItem().equals("Madhesh Pradesh")){
            fillAddress(key);
        }
        else if(pardesh.getSelectedItem().equals("Bagmati Pradesh")){
            fillAddress(key);
        }
        else if(pardesh.getSelectedItem().equals("Gandaki Pradesh")){
            fillAddress(key);
        }
        else if(pardesh.getSelectedItem().equals("Lumbini Pradesh")){
            fillAddress(key);
        }
        else if(pardesh.getSelectedItem().equals("Karnali Pradesh")){
            fillAddress(key);
        }
        else if(pardesh.getSelectedItem().equals("Sudur Paschim Pradesh")){
            fillAddress(key);
        }
        else{

            fillAddress(key);
        }
    }//GEN-LAST:event_pardeshItemStateChanged

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        male.setSelected(false);
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        female.setSelected(false);
    }//GEN-LAST:event_maleActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        DisplayRandomNum(5);

        FormValidation();

        String mysql = "INSERT INTO `voter`(`voter_id`, `fname`, `lname`, `mname`, `date_of_birth`, `father_name`, `mother_name`, `grand_father_name`, `gender`, `country`, `pardesh`, `district`, `Nagarpalika`, `oda_no`, `image`, `check_voted`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1)";
        try {
            pst = connection.prepareStatement(mysql);
            pst.setString(1, display_id.getText());
            pst.setString(2, txt_fname.getText());
            pst.setString(3, txt_lname.getText());
            pst.setString(4, txt_mname.getText());
            SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
            String date = dcn.format(dob.getDate() );
            pst.setString(5, date);
            pst.setString(6, txt_fathername.getText());
            pst.setString(7, txt_mothername.getText());
            pst.setString(8, txt_grandfname.getText());
            if(male.isSelected()){
                pst.setString(9, "Male");
            }else if(female.isSelected()){
                pst.setString(9, "Female");
            }else{
                JOptionPane.showMessageDialog(this, "Please select gender","Error",JOptionPane.ERROR_MESSAGE);
            }
            pst.setString(10, (String) district.getSelectedItem());
            pst.setString(11, (String) country.getSelectedItem());
            pst.setString(12, (String) pardesh.getSelectedItem());
            pst.setString(13, (String) muncipality.getSelectedItem());
            pst.setString(14, txt_woda.getText());
            pst.setBytes(15,personImg);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Done");
            //save.setEnabled(false);
            update.setEnabled(true);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        Clear();
    }//GEN-LAST:event_clearActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        mysql="UPDATE `voter` SET `fname`=?,`lname`=?,`mname`=?,`date_of_birth`=?,`father_name`=?,`mother_name`=?,`grand_father_name`=?,`gender`=?,`country`=?,`pardesh`=?,`district`=?,\n" +
        "`Nagarpalika`=?,`oda_no`=?,`image`=?,`check_voted`=1 WHERE voter_id='"+display_id.getText()+"'";
        try {
            pst=connection.prepareStatement(mysql);

            pst.setString(1, txt_fname.getText());
            pst.setString(2, txt_lname.getText());
            pst.setString(3, txt_mname.getText());
            SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
            String date = dcn.format(dob.getDate() );
            pst.setString(4, date);
            pst.setString(5, txt_fathername.getText());
            pst.setString(6, txt_mothername.getText());
            pst.setString(7, txt_grandfname.getText());
            if(male.isSelected()){
                pst.setString(8, "Male");
            }else if(female.isSelected()){
                pst.setString(8, "Female");
            }else{
                JOptionPane.showMessageDialog(this, "Please select gender","Error",JOptionPane.ERROR_MESSAGE);
            }
            pst.setString(9, (String) district.getSelectedItem());
            pst.setString(10, (String) country.getSelectedItem());
            pst.setString(11, (String) pardesh.getSelectedItem());
             pst.setString(12, (String) muncipality.getSelectedItem());
            pst.setString(13, txt_woda.getText());
            pst.setBytes(14,personImg);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Done");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_updateActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        VoterInformation obj=new VoterInformation();
        obj.setVisible(true);
    }//GEN-LAST:event_viewActionPerformed

    private void addnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewActionPerformed
        Clear();
        save.setEnabled(true);
        update.setEnabled(false);
    }//GEN-LAST:event_addnewActionPerformed

    private void display_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_display_idActionPerformed

    private void uploadimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadimgActionPerformed
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        fileName=f.getAbsolutePath();
        imgPath.setText(fileName);
        try {
            FileInputStream fis = new FileInputStream(f);
            ByteArrayOutputStream bAOS = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bAOS.write(buf, 0, readNum);
            }
            personImg = bAOS.toByteArray();
            byte[] citizone = personImg;
            ImageIcon formats = new ImageIcon(scaledImage(citizone, img.getWidth(), img.getHeight()));
            img.setIcon(formats);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_uploadimgActionPerformed

    private void FormValidation(){     
        
        if(txt_fname.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill First Name","Error",JOptionPane.ERROR_MESSAGE);
        }else if(txt_lname.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill mother name","Error",JOptionPane.ERROR_MESSAGE);
        }else if(txt_fathername.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill father ame","Error",JOptionPane.ERROR_MESSAGE);
        }else if(txt_mothername.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill mother name","Error",JOptionPane.ERROR_MESSAGE);
        }else if(txt_grandfname.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill grand father name","Error",JOptionPane.ERROR_MESSAGE);
        }else if(country.getSelectedItem().equals("Select Country")){
            JOptionPane.showMessageDialog(this, "Please Select Country","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(pardesh.getSelectedItem().equals("Select Pardesh")){
            JOptionPane.showMessageDialog(this, "Please Select Pardesh","Error",JOptionPane.ERROR_MESSAGE);
        }else if(district.getSelectedItem().equals("Select District")){
            JOptionPane.showMessageDialog(this, "Please Select District","Error",JOptionPane.ERROR_MESSAGE);
        }else if(muncipality.getSelectedItem().equals("Select Muncipality")){
            JOptionPane.showMessageDialog(this, "Please Select Muncipality","Error",JOptionPane.ERROR_MESSAGE);
        }else if(txt_woda.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Fill the Woda No","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }
    private void fillAddressDefault(){
        district.removeAllItems();
        muncipality.removeAllItems();
        
        district.addItem("Select District");
        muncipality.addItem("Select Muncipality/VDC");
        mysql="select * from district";
        try {
            pst=connection.prepareStatement(mysql);
            resultSet=pst.executeQuery();
            while(resultSet.next()){
                district.addItem(resultSet.getString("districtname"));
            }
        } catch (Exception e) {
        }
        String query="select * from muncipality";
        try {
            pst=connection.prepareStatement(query);
            resultSet=pst.executeQuery();
            while(resultSet.next()){
                muncipality.addItem(resultSet.getString("muncipalityname"));
            }
        } catch (Exception e) {
        }
    }
    private void fillAddress(String key){
        
     
        district.removeAllItems();
        district.addItem("Select District");
        mysql="SELECT district.districtname FROM district INNER JOIN pardesh ON pardesh.id = district.pardesh_id where pname='"+key+"'";
        try {
            pst=connection.prepareStatement(mysql);
            resultSet=pst.executeQuery();
            while(resultSet.next()){
               
                district.addItem(resultSet.getString("district.districtname"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    private void  FillTheAllField(String id){
        update.setEnabled(true);
        save.setEnabled(false);
        mysql="select * from voter where voter_id ='"+id+"'";
       
        try {
            pst = connection.prepareStatement(mysql);
            resultSet=pst.executeQuery();
            if(resultSet.next()){
                display_id.setText(resultSet.getString("voter_id"));
                txt_fname.setText(resultSet.getString("fname"));
                txt_mname.setText(resultSet.getString("mname"));
                txt_lname.setText(resultSet.getString("lname"));
                txt_fathername.setText(resultSet.getString("father_name"));
                txt_mothername.setText(resultSet.getString("mother_name"));
                txt_grandfname.setText(resultSet.getString("grand_father_name"));
                String dateValue = resultSet.getString("date_of_birth");
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);

                dob.setDate(date);
                if(resultSet.getString("gender").equals("Male")){
                    male.setSelected(true);
                    female.setSelected(false);
                }else{
                    female.setSelected(true);
                    male.setSelected(false);
                }
                String c=resultSet.getString("country");
                String p=resultSet.getString("pardesh");
                String d=resultSet.getString("district");
                String m=resultSet.getString("Nagarpalika");
                txt_woda.setText(resultSet.getString("oda_no"));
                country.setSelectedIndex(1);
                pardesh.setSelectedIndex(1);

            byte[] imageData = resultSet.getBytes("image");
            ImageIcon format = new ImageIcon(scaledImage(imageData, img.getWidth(), img.getHeight()));
            img.setIcon(format);
            }
        } catch (Exception e) {
            
        }
    }
    
    private Image scaledImage(byte[] img, int w, int h) {
        BufferedImage resizeImage = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        try {
            Graphics2D g2 = resizeImage.createGraphics();
            g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);

            //convert the byte array back to buffered image
            ByteArrayInputStream in = new ByteArrayInputStream(img);
            BufferedImage bImageFromConvert = ImageIO.read(in);

            g2.drawImage(bImageFromConvert, 0, 0, w, h, null);
            g2.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        return resizeImage;
    }
    
    private void DisplayRandomNum(int length) {
        StringBuilder str = new StringBuilder();
        for (int i = 0; i < length; i++) {
            int num = getRandom();
            char ch = char_list.charAt(num);
            str.append(ch);
        }
        display_id.setText(str.toString());

    }

    private int getRandom() {
        int randomInt = 0;
        Random randomGenerator = new Random();
        randomInt = randomGenerator.nextInt(char_list.length());
        if (randomInt - 1 == -1) {
            return randomInt;
        } else {
            return randomInt - 1;
        }
    }
        
    private void Clear(){
        txt_fname.setText(null);
        txt_lname.setText(null);
        txt_mname.setText(null);        
        txt_fathername.setText(null);
        txt_mothername.setText(null);
        txt_grandfname.setText(null);         
         male.setSelected(false);
         female.setSelected(false);
         country.setSelectedIndex(0);
         pardesh.setSelectedIndex(0);
         district.setSelectedIndex(0);
         muncipality.setSelectedIndex(0);
         search.setText("");     
         
        txt_woda.setText(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVoter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnew;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> country;
    private javax.swing.JTextField display_id;
    private javax.swing.JComboBox<String> district;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel img;
    private javax.swing.JTextField imgPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton male;
    private javax.swing.JComboBox<String> muncipality;
    private javax.swing.JComboBox<String> pardesh;
    private javax.swing.JButton save;
    private javax.swing.JTextField search;
    private javax.swing.JTextField txt_fathername;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_grandfname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_mname;
    private javax.swing.JTextField txt_mothername;
    private javax.swing.JTextField txt_woda;
    private javax.swing.JButton update;
    private javax.swing.JButton uploadimg;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
