/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.voting.Voter;

import Card.Card;
import e.voting.DbConnect;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DELL
 */
public class VoterInformation extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    String voter_id="";
    static VoterInformation obj=null;
    public VoterInformation() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        conn=DbConnect.DbConnect();
        setTitle("Voter Information");
        setResizable(false);
        updateVoterInfo();
        setLocationRelativeTo(null);
    }
    
    public static VoterInformation getObj(){
        if(obj==null){
            obj=new VoterInformation();
        }return obj;
    }
    private void setId(String id){
        voter_id=id;
    }
    private String getId(){
        return voter_id;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VoterInfo_tbl = new javax.swing.JTable();
        combo_search = new javax.swing.JComboBox<>();
        search_txt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        voter_img = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VoterInfo_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        VoterInfo_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoterInfo_tblMouseClicked(evt);
            }
        });
        VoterInfo_tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VoterInfo_tblKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(VoterInfo_tbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1130, 260));

        combo_search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Voter Id", "Name", "Father Name", "Mother Name", "District and Name", "Muncipality And Name", " " }));
        jPanel1.add(combo_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 99, 30));

        search_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        search_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_txtKeyReleased(evt);
            }
        });
        jPanel1.add(search_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 170, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Voter Image", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 153))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(voter_img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(voter_img, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, -1, 200));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/073_view_show-20.png"))); // NOI18N
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, 30));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trash-circle-red-20.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 110, 30));

        Edit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/document-20_1.png"))); // NOI18N
        Edit.setText("EDIT");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel1.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, 30));

        Add.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/163_plus_add_new-20.png"))); // NOI18N
        Add.setText("ADD");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Printer-24.png"))); // NOI18N
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 100, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Voter Information");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 219, 45));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/23-512.png"))); // NOI18N
        jButton3.setText("Search");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 100, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/addvimg1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1130, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Image scaledImage(byte[] img, int w, int h) {
        BufferedImage resizeImage = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        try {
            Graphics2D g2 = resizeImage.createGraphics();
            g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);

            //convert the byte array back to buffered image
            ByteArrayInputStream in = new ByteArrayInputStream(img);
            BufferedImage bImageFromConvert = ImageIO.read(in);

            g2.drawImage(bImageFromConvert, 0, 0, w, h, null);
            g2.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        return resizeImage;
    }
    
    private void GetValue(String key){
        
        try {              
              String mysql="select voter_id as 'Voter ID',  fname as 'First Name'"
                      + " ,lname as 'Last Name', mname as 'Middle Name', date_of_birth as 'DOB', father_name as 'Father Name',"
                      + " mother_name as 'Mother Name', grand_father_name as 'Grand Father Name', gender as 'Gender',"
                      + " district as 'District', Nagarpalika as 'Muncipality', oda_no as 'Woda No' from voter "+key;
              //JOptionPane.showMessageDialog(rootPane, mysql);
              pst=conn.prepareStatement(mysql);
              rs=pst.executeQuery();
              VoterInfo_tbl.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            
        }
        
    }
    private void search_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_txtKeyReleased
        String search_id=(String) combo_search.getSelectedItem();
      
           Search(search_id);               
        
    }//GEN-LAST:event_search_txtKeyReleased

    private void VoterInfo_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoterInfo_tblMouseClicked
        try {
            int row = VoterInfo_tbl.getSelectedRow();            
            String tableClick = (VoterInfo_tbl.getModel().getValueAt(row, 0).toString());
            setId(tableClick);
            String mysql = "select * from voter where voter_id='" + tableClick + "'";
            pst = conn.prepareStatement(mysql);
            rs = pst.executeQuery();
            if (rs.next()) {
                getValue();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_VoterInfo_tblMouseClicked

    private void VoterInfo_tblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VoterInfo_tblKeyReleased
        try {
            int row = VoterInfo_tbl.getSelectedRow();
            String tableClick = (VoterInfo_tbl.getModel().getValueAt(row, 0).toString());
            String mysql = "select * from voter where voter_id='" + tableClick + "'";
            pst = conn.prepareStatement(mysql);
            rs = pst.executeQuery();
            if (rs.next()) {
                getValue();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_VoterInfo_tblKeyReleased

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int conf=JOptionPane.showConfirmDialog(this,"Do you want to delete?","Delete",JOptionPane.YES_NO_OPTION);
        if(conf==0){
        int row = VoterInfo_tbl.getSelectedRow();
        String tableClick = (VoterInfo_tbl.getModel().getValueAt(row, 0).toString());
    
        String mysql = "DELETE FROM `voter` WHERE  voter_id='" +tableClick + "'";
        try {
            pst=conn.prepareStatement(mysql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Deleted");
            updateVoterInfo();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
            if(getId().equals(""))
            {
                JOptionPane.showMessageDialog(rootPane, "Sorry, You are not selected the voter please select the voter. Thank you!");
            }else{
                Card d=new Card(getId());
                d.setVisible(true);
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
       AddVoter b=new AddVoter();
       b.setVisible(true);
    }//GEN-LAST:event_AddActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
       if(voter_id.equalsIgnoreCase("")){
           JOptionPane.showMessageDialog(this, "Please Choose the Voter", "Error", JOptionPane.ERROR_MESSAGE);
       }else{
           int row = VoterInfo_tbl.getSelectedRow();
            String tableClick = (VoterInfo_tbl.getModel().getValueAt(row, 0).toString());
           AddVoter b=new AddVoter(tableClick);
           b.setVisible(true);
           
       }
    }//GEN-LAST:event_EditActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    private void getValue(){
         try {
             byte[] imageData = rs.getBytes("image");
            ImageIcon format = new ImageIcon(scaledImage(imageData, voter_img.getWidth(), voter_img.getHeight()));
            voter_img.setIcon(format);
            byte[] citizone = rs.getBytes("citizone_image");
            
        } catch (Exception e) {
        }
    }
    private void Search(String key){
          /*Voter Id,Name,Father Name,Mother Name, District and Name, Muncipality And Name
           */
          String value=search_txt.getText();
         
          if(key.equals("Voter Id")){
              if(value.equals("")){
                  String s=" ";
                    GetValue(s);
              }else{
                String s="where voter_id like '"+value+"%'";
                GetValue(s);
              }
          }
          if(key.equals("Name")){
              if(value.equals("")){
                  String s=" ";
                    GetValue(s);
              }else{
                String s="where fname like '"+value+"%'";
                GetValue(s);
              }
          }
          if(key.equals("Father Name")){
              if(value.equals("")){
                  String s=" ";
                    GetValue(s);
              }else{
                String s="where father_name like '"+value+"%'";
                GetValue(s);
              }
          }
          if(key.equals("Mother Name")){
              if(value.equals("")){
                  String s=" ";
                    GetValue(s);
              }else{
                String s="where mother_name like '"+value+"%'";
                GetValue(s);
              }
          }
          if(key.equals("District and Name")){
              if(value.equals("")){
                  String s=" ";
                    GetValue(s);
              }else{
                String s="where district like '"+value+"%'";
                GetValue(s);
              }
          }
          if(key.equals("Muncipality And Name")){
              if(value.equals("")){
                  String s=" ";
                    GetValue(s);
              }else{
                String s="where Nagarpalika like '"+value+"%'";
                GetValue(s);
              }
          }
          

    }
    
    private void updateVoterInfo(){
        String s=" ";
        GetValue(s);
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoterInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoterInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoterInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoterInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoterInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Edit;
    private javax.swing.JTable VoterInfo_tbl;
    private javax.swing.JComboBox<String> combo_search;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search_txt;
    private javax.swing.JLabel voter_img;
    // End of variables declaration//GEN-END:variables
}
